spring:
  application:
    name: company-search-demo
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: test
    password: test
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    com.risk: DEBUG


true-proxy:
  base-url: 'https://exercise.trunarrative.cloud/TruProxyAPI/rest/Companies/v1'
#  cache:
#    enabled: true
#    cache-size: 100
#    cache-duration-millis: 36000
